layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    forks: false
    projects:
    # - repo-name

social_media:
#   behance: your_username
#   dribbble: your_username
#   facebook: your_username
#   hackerrank: your_username
#   instagram: your_username
#   keybase: your_username
  linkedin: guystone
  # medium: your_username
  stackoverflow: 11003094
#   telegram: your_username
  twitter: guy_stone
#   unsplash: your_username
#   vk: your_username
website: http://guystone.github.io
#   youtube: your_username

experience_settings:
  limit: 2
  masthead: false
  exclude:
    details: false
    # TODO: fix size of div when details are excluded
  # sort_by: pushed
  # # sort_by options:
  # #   - pushed
  # #   - stars
  # exclude:
  #   forks: false
  #   projects:
  #   # - repo-name

education_settings:
  limit: 2
  masthead: false
  exclude:
    details: false
    # TODO: fix size of div when details are excluded

education:
    - degree: BSc in Computer Science
      university: King's Colege London
      time: 2016 - 2019
      details: |
        1st Year Modules: Programming Practice and Applications, Data Structures, Database Systems, Computer Systems, Introduction to Artificial Intelligence, Foundations of Computing, Elementary Logic with Applications.

        2st Year Modules: Software Engineering Group Project, Practical Experiences of Programming, Object-Oriented Specification and Design, Internet Systems, Foundations of Computing 2, Operating Systems and Concurrency, Programming Language Design Paradigms.

    # - degree: MSc in Computer Science
    #   university: Bristol University
    #   time: 2007 - 2011
    #   details: |
    #     Describe your study here lorem ipsum dolor sit amet, consectetuer
    #     adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum
    #     sociis natoque penatibus et magnis dis parturient montes, nascetur
    #     ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu,
    #     pretium quis, sem.



experiences:
    - role: Software Engineer Intern
      time: June 2017 - September 2017
      company: Zalando SE, Berlin
      details: |
        Completed a three-month internship with Zalando where I worked
        as a Software Development Engineer Intern, this allowed for a first-hand
        experience in a professional environment, under agile methodologies.
        These three months involved me designing and building a scalable media
        management REST microservice. Working with Scala, AWS, REST, AKKA Http, Swagger.

    # - role: Senior Software Engineer
    #   time: 2014 - 2015
    #   company: Google, London
    #   details: |
    #     Describe your role here lorem ipsum dolor sit amet, consectetuer
    #     adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa.
    #     Cum sociis natoque penatibus et magnis dis parturient montes,
    #     nascetur ridiculus mus. Donec quam felis, ultricies nec,
    #     pellentesque eu, pretium quis, sem.

topics:
  - name: Java
    web_url: https://github.com/topics/java
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/java/java.png

  - name: Python
    web_url: https://github.com/topics/python
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/python/python.png

  - name: Swift
    web_url: https://github.com/topics/swift
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/swift/swift.png
